Functions for checking the current token, uploading a file. Http status code handling.

diff --git a/get_folder_id b/get_folder_id
--- a/get_folder_id
+++ b/get_folder_id
@@ -3,4 +3,15 @@
 FOLDER_NAME=$1
 TOKEN=`cat box_token.json | jq -r '.access_token'`
 QUERY=`echo ".entries[]|select(.name==\"$FOLDER_NAME\")|.id"`
-curl -s https://api.box.com/2.0/folders/0/items -H "Authorization: Bearer ${TOKEN}" | jq -r $QUERY
+HTTP_CODE=`curl -s https://api.box.com/2.0/folders/0/items -H "Authorization: Bearer ${TOKEN}" -w '%{http_code}\n' -o get_folder_id_response`
+if [ $HTTP_CODE == 200 ] ; then
+  FOLDER_ID=`cat get_folder_id_response | jq -r $QUERY`
+  if [ "$FOLDER_ID" == "" ] ; then
+    echo "ID Not Found."
+    exit 1
+  fi
+  echo $FOLDER_ID
+  exit 0
+fi
+echo "Error in get_folder_id : http status code is $HTTP_CODE"
+exit 2
diff --git a/refresh_token b/refresh_token
--- a/refresh_token
+++ b/refresh_token
@@ -4,6 +4,15 @@ REFRESH_TOKEN=`cat box_token.json | jq -r '.refresh_token'`
 CLIENT_ID=`cat box_client.json | jq -r '.client_id'`
 CLIENT_SECRET=`cat box_client.json | jq -r '.client_secret'`
 
-mv -f box_token.json box_token.bk
 BODY="grant_type=refresh_token&refresh_token=${REFRESH_TOKEN}&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}"
-curl -s https://api.box.com/oauth2/token -d ${BODY} -X POST | jq '.' > box_token.json
+HTTP_CODE=`curl -s https://api.box.com/oauth2/token -d ${BODY} -X POST -w '%{http_code}\n' -o refresh_token_response`
+if [ $HTTP_CODE == 200 ] ; then
+  mv -f box_token.json box_token.bk
+  cat refresh_token_response | jq '.' > box_token.json
+  echo "New token:"
+  cat box_token.json
+  exit 0
+fi
+echo "Error in refresh_token : http status code is $HTTP_CODE"
+exit 2
+
